### ISSUE TITLE
shellHook not used when run "directly"

### ISSUE THREAD

**Issue by mtalexan** [christianharke/podman-shell-flake#1]
When running the flake directly,the shellHook configured in the default.nix is never run. 
This results in there being no configuration files for podman to use.

I'm not sure why it's not being run, but it's unusable for first-time one-shot use without the shellHook or manual population of the missing files.

**Comment by christianharke** [comment]
This is indeed an issue. Would you mind if we remove the ability of running it this way, since its primary use case is to have it inside a nix development shell? Otherwise, we can state in the README, that the shellHook needs to be run before use.

**Comment by mtalexan** [comment]
Yeah, that probably makes the most sense. I only tried it because it was in the documentation in the first place, so even removing it from the README is probably sufficient. There might conceivably be some use for having it still defined in the flake.nix as an app, so you could probably leave it in there even.
